### ISSUE TITLE
98_MAX_Temperatur: Fehler bei Modusumschaltung

### ISSUE THREAD

**Issue by dkadioglu** [bismosa/FHEM#1]
Wenn ich eine Gruppe von Thermostaten in den Modus auto oder manuell versetzen will und dabei keine Temperatur angebe - diese sollte nach meinem Verständnis optional sein - erhalte ich folgende Ausgabe im Log:

2019.11.03 21:46:49 1: PERL WARNING: Argument "---" isn't numeric in multiplication (*) at /usr/share/fhem/FHEM/10_MAX.pm line 324.
2019.11.03 21:46:49 1: PERL WARNING: Use of uninitialized value $ATtxt in concatenation (.) or string at /usr/share/fhem/FHEM/98_MAX_Temperatur.pm line 267.

Der Modus wird aber dennoch umgeschaltet.

**Comment by bismosa** [comment]
Schaue ich mir dann auch ebenfalls an :)

Bitte etwas Geduld...ich bin derzeit etwas vollgepackt...

Gruß
Bismosa

**Comment by bismosa** [comment]
Hallo!
Hier wurde es etwas schwieriger, da ich den Fehler nur sehr schwer nachstellen konnte.
Ich habe hier einige Fehler bereinigt. 
Offen ist allerdings noch, die Fehlermeldung vom Max-Modul. Das Max-Modul erwartet eine Temperaturangabe. Besteht diese aus "---" wird vermutlich die zuletzt gültige Temperatur gewählt (Bitte mal testen, welche das ist!). Ich weiß nicht, wie ich dies umgehen kann...

Bitte ein Update machen und testen. Danke!

Gruß
Bismosa

**Comment by dkadioglu** [comment]
Nach dem Update und einem Neustart konnte ich folgendes beobachten:
1. Thermostat ist im Modus Auto mit 19,5 °C
2. Umschaltung in Modus Manuell mit ---
3. Fehler: PERL WARNING: Argument "---" isn't numeric in multiplication (*) at /usr/share/fhem/FHEM/10_MAX.pm line 324.
4. Umschaltung in Modus Auto mit ---
5. Kein Fehler
6. Umschaltung in Modus Manuell mit ---
7. Kein Fehler
8. Neustart FHEM
9. Umschaltung in Modus Auto mit ---
10. Fehler: PERL WARNING: Argument "---" isn't numeric in multiplication (*) at /usr/share/fhem/FHEM/10_MAX.pm line 324.
11. Umschaltung in Modus Manuell mit ---
12. Kein Fehler
13. Umschaltung in Modus Auto mit ---
14. Kein Fehler

Der Fehler schein also nur einmal nach einem Neustart aufzutauchen. Als Temperatur bleibt dann wohl die aktuell Eingestellte bestehen.
Wenn ich noch weitere Dinge ausprobieren soll, bitte melden.
Danke auf jeden Fall fürs (sehr schnelle) Analysieren!

**Comment by bismosa** [comment]
Hallo!

Ich kann es derzeit leider nicht selbst probieren. Versuche mal bitte folgendes:
- Einstellung manuell -> Temperatur z.B. auf 12,5°C stellen
- Einstellung Auto -> Temperatur z.B. auf 17,5°C stellen
- Umstellung mit dem Modul Auto - Manuell -> Welche Temperatur wird angezeigt?
- Umstellung mit dem Modul Manuell - Auto -> Welche Temperatur wird nun angezeigt?
- Welche Temperaturen werden angezeigt, wenn die Umstellung direkt am HT vorgenommen werden?

Warum der Fehler im Max-Modul nur 1x auftaucht ist mir ein rätsel. Es wird halt eine Temperatur (numerischer Wert) erwartet...den habe ich nicht zur Verfügung (btw. vielleicht findest Du ein Reading, das diese Temperaturen angibt?)...
Wenn dies so wäre, dann muss ich den Fehler leider so drin lassen. Wir könnten hier höchstens Versuchen im Max-Modul den Fehler ausfindig zu machen und dies dem Maintainer melden...aber erstmal schauen wir, ob es eine andere Möglichkeit gibt.

Gruß
Bismosa

**Comment by dkadioglu** [comment]
Also nach ein wenig Ausprobieren vermute ich, dass der Thermostat den zuletzt eingestellten Wert im Modus Manuell speichert:
1. Thermostat ist in Modus Manuell und eingestellte Temperatur ist 17.5
2. Thermostat wird mit dem Knopf am Thermostaten in Modus Auto geschaltet und die im Wochenprofil vorgesehene Temperatur von 19.5 wird eingestellt
3. Thermostat wird mit dem Knopf am Thermostaten in Modus Manuell geschaltet und es wird wieder die Temperatur 17.5 eingestellt

Mein Vorschlag wäre hier, das Modul MAX so zu erweitern, dass es Modus-Umschaltungen ohne Temperatur zulässt. Mit dem folgenden Patch funktionierts bei mir ohne Fehler/Warnungen im Log:

```
--- 10_MAX.pm	2019-11-09 10:31:57.426229800 +0100
+++ 10_MAX.pm	2019-11-09 11:50:37.188785908 +0100
@@ -273,6 +273,8 @@
           $temperature = MAX_ReadingsVal($hash,"ecoTemperature");
         } elsif($args[1] eq "comfort") {
           $temperature = MAX_ReadingsVal($hash,"comfortTemperature");
+        } elsif($args[0] =~ /\D/) {
+          $temperature = 0; #use last manual set temperature
         } else {
           $temperature = MAX_ParseTemperature($args[1]);
         }
@@ -307,6 +309,8 @@
         $temperature = MAX_ReadingsVal($hash,"ecoTemperature");
       } elsif($args[0] eq "comfort") {
         $temperature = MAX_ReadingsVal($hash,"comfortTemperature");
+      } elsif($args[0] =~ /\D/) {
+          $temperature = 0; #use last manual set temperature
       } else {
         $temperature = MAX_ParseTemperature($args[0]);
       }
```

Das Interessante ist nun aber, dass die Modus-Umschaltung ohne Temperatur (---) mit Deinem Modul dazu führt, dass bei Umschaltung von Auto auf Manuell dann dieselbe Temperatur eingestellt wird, die in Auto aktiv war - obwohl vorher über den Thermostaten im Modus Manuell eine andere Temperatur eingestellt war. Das MAX-Modul scheint also irgendwas anders zu machen, als die Modus-Taste am Thermostaten. Mein Patch führt jedenfalls dazu, dass die Zeile
`my $payload = sprintf("%02x",int($temperature*2.0) | ($ctrlmode << 6));`
eine Temperatur von 0 mit 2.0 multipliziert. Zumindest ist die Warnung verschwunden.

Hast Du noch andere Ideen dazu?
FYI: Es gibt momentan wohl keinen Maintainer für das Modul 10_MAX.pm. Patches werden ggf. von Rudolf Koenig angenommen und übernommen.

**Comment by bismosa** [comment]
Hallo,

danke, das Du Dich hier an der Problemlösung beteiligst :)

Wenn mein Test gerade richtig war, dann ist das Verhalten aber mit dem Patch gleich geblieben? Bei Modusumschaltung wird immer die Auto-Temperatur gesetzt? 
Interessant wäre, ob es eine Möglichkeit gibt zwischen Auto und Manu umzuschalten ohne die Temperatur zu verändern (also die Temperatur aus dem Thermostaten zu verwenden)...dafür müsste man aber ganz tief in das Modul einsteigen...dazu fehlt mir im Moment die Zeit...auch wenn es mich reizt.

Hast Du eine Idee, warum die Fehlermeldung nur einmalig erfolgt?

Vielleicht sollten wir, bevor wir den Patch bei Rudolf einreichen, die Umschaltung nach Möglichkeit verbessern :)

Gruß
Bismosa

**Comment by dkadioglu** [comment]
Ja genau, mein Patch sorgt meiner Erkenntnis nach nur dafür, dass die Fehlermeldung ausbleibt. Für die Modusumschaltung ohne Temperatur müsste man sicherlich tiefer in das Protokoll einsteigen. Wenn ich den Code richtig interpretiere, wird bei Weglassen einer Temperaturangabe einfach eine 0 für die Temperatur eingesetzt.  Ich stelle mir aber gerade die Frage, wie es sich mit MAX-Software und MAX Cube verhält. Ich habe leider keinen. Hast Du einen MAX Cube und könntest mal testen, ob da eine Modus-Umschaltung ohne Temperatur möglich ist?

**Comment by bismosa** [comment]
Hallo,

wenn es derzeit "nur" die Fehlerunterdrückung ist, ist es ja auch schon sehr hilfreich :)

Ich habe leider auch keinen Cube...ich hätte noch einen Wandthermostaten...aber der speichert vermutlich den Wert selbst, da ja alles synchronisiert wird.

Hast Du die Muße dich ins Protokoll einzuarbeiten bzw. Lust da noch weitere Tests zu machen? Ich bin ja erstaunt, das es mit einer Temperatur von "0" funktioniert. Rein logisch hätte ich gedacht, dass dann in den Modus "off" geschaltet wird.

Sorry...ich habe derzeit leider keine Zeit mi ch damit zu beschäftigen...

Gruß
Bismosa

**Comment by dkadioglu** [comment]
Ich bin mir ehrlich gesagt nicht sicher, was genau dann letztendlich übertragen wird. Ich fürchte, dass wir ohne jemanden mit Cube wenig Möglichkeiten haben. Zumindest nach meiner Recherche ist es mir nicht gelungen, auch nur ansatzweise Doku über das Funkprotokoll zu finden.

Das mit der Temperatur von 0 habe ich im Grunde ja auch nur geklaut, in Zeile 279-280 lautet es:
`
} elsif(@args == 1) {
$temperature = 0; #use temperature from weekly program
`
Für die Umschaltung in den Modus auto ist also explizit vorgesehen, die Temperatur wegzulassen. Das habe ich dann analog für die Umschaltung in manual nachgebaut.

Momentan sehe ich leider auch keine Möglichkeit, mich tiefergehend damit zu beschäftigen. Dementsprechend würde ich vorschlagen, zunächst mal den Patch für die Verhinderung der Warnung einzureichen, damit Dein Modul diesen zumindest nicht mehr auslöst. Die Möglichkeit in den Modus manual zu schalten und dabei für jeden Thermostat die gerade eingestellte desiredTemperature beizubehalten ist aus meiner Sicht ja gut!

Hab den Kommentar aber nochmal angepasst, da meine Vermutung, dass der Thermostat die zuletzt als manuell eingestellte Temperatur übernimmt, ja nicht stimmte:

```
--- 10_MAX.pm	2019-11-09 10:31:57.426229800 +0100
+++ 10_MAX.pm	2019-11-09 11:50:37.188785908 +0100
@@ -273,6 +273,8 @@
           $temperature = MAX_ReadingsVal($hash,"ecoTemperature");
         } elsif($args[1] eq "comfort") {
           $temperature = MAX_ReadingsVal($hash,"comfortTemperature");
+        } elsif($args[0] =~ /\D/) {
+          $temperature = 0; #use currently set temperature
         } else {
           $temperature = MAX_ParseTemperature($args[1]);
         }
@@ -307,6 +309,8 @@
         $temperature = MAX_ReadingsVal($hash,"ecoTemperature");
       } elsif($args[0] eq "comfort") {
         $temperature = MAX_ReadingsVal($hash,"comfortTemperature");
+      } elsif($args[0] =~ /\D/) {
+          $temperature = 0; #use currently set temperature
       } else {
         $temperature = MAX_ParseTemperature($args[0]);
       }
```

Was meinst Du?

**Comment by bismosa** [comment]
Hallo!
Danke für deine Bemühungen! 
Zum Protokoll hatte ich schon Mal was gefunden:
https://github.com/Bouni/max-cube-protocol
https://www.mikrocontroller.net/topic/244432
Diese Seite ist leider down...aber im webarchiv zu finden und sehr interessant:
http://blog.hekkers.net/2011/08/29/unravelling-the-elv-max-heating-control-system-protocol/

Leider bin ich nie dazu gekommen mir das Mal genauer anzuschauen...

Ich finde deine Idee richtig gut! Muss aber ehrlich sagen, das ich lieber die vorherige gespeicherte manuelle Temperatur besser finden würde. Aber es scheint nicht machbar.

Der Patch wäre also bis auf weiteres sehr hilfreich. Wäre schön wenn du den einreichen könntest :)

Danke!

Gruß
Bismosa

**Comment by dkadioglu** [comment]
Hallo nochmal,

danke für die Links. Schaue ich mir bei Gelegenheit mal an.
Ich hab nochmal über das Ganze nachgedacht und möchte Dir noch einen anderen Vorschlag machen:
```
#Es muss eine Temperatur übermittelt werden. 
    #Wird ein --- übertragen kommt es zu einem Log-Eintrag der Modus wird aber umgeschaltet
    #if ("$temp" eq "---"){
    #  $temp = "";
    #}
```
Nachdem ich diese Stelle in Deinem Code gefunden habe, kam mir der Gedanke, dass ein deutlich einfacheres Vorgehen möglich wäre. Und zwar könntest Du aus `$temp = ""` eher  `$temp = 0` machen. Nach Einkommentierung dieses modifizierten Codes funktioniert die  Umschaltung in manual ohne Temperatur mit Deinem Modul ohne Fehler im Log und ohne den Patch für das MAX-Modul. Was hältst Du davon?

**Comment by bismosa** [comment]
Hallo!

Gute Idee :) Wenn eh mit der Temperatur von 0 gearbeitet wird ist das die bessere Lösung!

Ich bin derzeit unterwegs und kann es nicht sofort nachpflegen...sorry.

Ich versuche es so schnell wie möglich nachzuholen.

Danke!

Gruß
Bismosa

**Comment by bismosa** [comment]
Hallo,

ich habe nun endlich das Update eingespielt. Bitte testen :)
Danke für die Hilfe!

Gruß
Bismosa

**Comment by dkadioglu** [comment]
Hallo,

funktioniert soweit, vielen Dank!
Du kannst das Ticket dann gerne schließen.

Gruß

**Comment by bismosa** [comment]
OK. Danke für die Rückmeldung!
Ich schließe das hier...wir behalten das aber mal im Hinterkopf... vielleicht lässt sich das ja irgendwann anders lösen :)

Gruß
Bismosa
