### ISSUE TITLE
98_MAX_Temperatur: Optimierung der Darstellung

### ISSUE THREAD

**Issue by dkadioglu** [bismosa/FHEM#2]
Wenn ich im Dropdown eine Gruppe auswähle, werden darunter alle dieser Gruppe zugeordneten Thermostate und einige derer Readings angezeigt, soweit so gut:
Mode:auto keepAuto:? Temp:20.7°C desiredTemp:19.5°C (MAX_xxxxxx)

Da ich für jeden Thermostat aber auch Aliase definiert habe, wäre es aus meiner Sicht hilfreicher, in der Klammer statt des Device-Namens eben den Alias anzuzeigen. Wäre es möglich, dies zu ändern?

**Comment by bismosa** [comment]
Schaue ich mir an :)

**Comment by bismosa** [comment]
Hallo!

Wenn ein Alias vorhanden ist, wird dieser nun angezeigt. Ansonsten der Gerätename.
Bitte ein Update machen und testen. Danke!

Gruß
Bismosa

**Comment by dkadioglu** [comment]
Nach dem Update werden nun meine Aliase angezeigt. Perfekt! Vielen Dank!
Schließe das Ticket damit.
