### ISSUE TITLE
98_MAX_Temperatur: Initialzustand Dropdown

### ISSUE THREAD

**Issue by dkadioglu** [bismosa/FHEM#3]
Da erst nach Auswahl eines Eintrages im Dropdown für die Auswahl des Gerätes bzw. der Gruppe die relevanten Geräte und deren Readings geladen und dargestellt werden, entsteht folgendes Problem:
Beim ersten Laden der Seite ist im Dropdown der erste Eintrag vorausgewählt, die relevanten Geräte und deren Readings werden aber nicht geladen. Erst wenn einer der anderen Einträge in diesem Dropdown ausgewählt wird, funktioniert das Ganze wie gewünscht. Dies liesse sich aus meiner Sicht dadurch beheben, dass das Dropdown einen leeren Eintrag bekommt, genauso wie bei den anderen Dropdowns könnte dies --- beinhalten. Das heißt, beim initialen Laden der Seite wäre dieser Eintrag vorausgewählt und es müssten dann ja auch keine Geräte und deren Readings dazu geladen/angezeigt werden. Wäre es möglich, das Verhalten entsprechend anzupassen?

**Comment by bismosa** [comment]
Hallo!

Danke für die Rückmeldungen und Tipps zur Fehlerbehebung. :)

Ich muss mir das in Ruhe mal die Tage anschauen. Möglich ist das bestimmt...da es aber nur nach der ersten Initialisierung (ich glaube auch nach einem FHEM-Neustart) passiert, habe ich dieses Problem erstmal ignoriert.

Ich schaue es mir an, wenn ich etwas Zeit finde.

Gruß
Bismosa

**Comment by bismosa** [comment]
Hallo!
Ich habe das nun so umgesetzt, das nach einer Initialisierung ein zusätzlicher Eintrag "---" im DropDown vorhanden ist. Sobald ein Device ausgewählt wird, verschwindet dies wieder.
Bitte ein Update machen und testen. Danke!

Gruß
Bismosa

**Comment by dkadioglu** [comment]
Nach dem Update wird nach einem Neustart wie beschrieben --- angezeigt, nach Auswahl eines der anderen Einträge ist --- wieder verschwunden. Scheint soweit zu funktionieren. Würde dies noch ein paar Tage beobachten und dann Rückmeldung geben.
Vielen Dank auf jeden Fall schon mal!

**Comment by dkadioglu** [comment]
Das Ganze funktioniert bisher wie gewünscht. Vielen Dank nochmal. Schließe das Issue damit.
